// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaStream.Persistence.Data.Contexts;

#nullable disable

namespace NovaStream.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230216152444_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "American actor and producer Matthew David McConaughey was born in Uvalde, Texas. His mother, Mary Kathleen (McCabe), is a substitute school teacher originally from New Jersey. His father, James Donald McConaughey, was a Mississippi-born gas station owner who ran an oil pipe supply business. He is of Irish, Scottish, German, English, and Swedish descent. Matthew grew up in Longview, Texas, where he graduated from the local High School (1988). Showing little interest in his father's oil business, which his two brothers later joined, Matthew was longing for a change of scenery, and spent a year in Australia, washing dishes and shoveling chicken manure. Back to the States, he attended the University of Texas in Austin, originally wishing to be a lawyer. But, when he discovered an inspirational Og Mandino book \"The Greatest Salesman in the World\" before one of his final exams, he suddenly knew he had to change his major from law to film.",
                            ImageUrl = "Images/Actors/Matthew-McConaughey-image.jpg",
                            Name = "Matthew",
                            Surname = "McConaughey"
                        },
                        new
                        {
                            Id = 2,
                            About = "Anne Jacqueline Hathaway was born in Brooklyn, New York, to Kate McCauley Hathaway, an actress, and Gerald T. Hathaway, a lawyer, both originally from Philadelphia. She is of mostly Irish descent, along with English, German, and French. Her first major role came in the short-lived television series Get Real (1999). She gained widespread recognition for her roles in The Princess Diaries (2001) and its 2004 sequel as a young girl who discovers she is a member of royalty, opposite Julie Andrews and Heather Matarazzo.",
                            ImageUrl = "Images/Actors/Anne-Hathaway-image.jpg",
                            Name = "Anne",
                            Surname = "Hathaway"
                        },
                        new
                        {
                            Id = 3,
                            About = "Jessica Michelle Chastain was born in Sacramento, California, and was raised in a middle-class household in a Northern California suburb. Her mother, Jerri Chastain, is a vegan chef whose family is originally from Kansas, and her stepfather is a fireman. She discovered dance at the age of nine and was in a dance troupe by age thirteen. She began performing in Shakespearean productions all over the Bay area.",
                            ImageUrl = "Images/Actors/Jessica-Chastain-image.jpg",
                            Name = "Jessica",
                            Surname = "Chastain"
                        },
                        new
                        {
                            Id = 4,
                            About = "Pedro Pascal is a Chilean-born actor. He is best known for portraying the roles of Oberyn Martell in the fourth season of the HBO series Game of Thrones (2011), Javier Peña in the Netflix series Narcos (2015), the titular character in the Disney+ series The Mandalorian (2019) and Joel Miller in the HBO series The Last of Us (2023).",
                            ImageUrl = "Images/Actors/Pedro-Pascal-image.jpg",
                            Name = "Pedro",
                            Surname = "Pascal"
                        },
                        new
                        {
                            Id = 5,
                            About = "Bella Ramsey made her professional acting debut as fierce young noblewoman Lyanna Mormont in Season 6 of HBO's 'Game of Thrones', a role that quickly became a fan favorite and saw Bella return for the next 2 seasons. Bella will be returning to HBO as the leading role of 'Ellie Williams' in their new flagship show 'The Last of Us' opposite Pedro Pascal. Bella is also known for playing the titular character Mildred Hubble in the newest adaptation of 'The Worst Witch' for which she won the Young Performer BAFTA in 2019. Bella lends her voice to 'Hilda', an award winning animation series for Netflix. Bella was recently on screens in the second season of BBC/HBO's adaptation of 'His Dark Materials'.",
                            ImageUrl = "Images/Actors/Bella-Ramsey-Image.jpg",
                            Name = "Bella",
                            Surname = "Ramsey"
                        },
                        new
                        {
                            Id = 6,
                            About = "Gabriel Luna was born on December 5, 1982 in Austin, Texas, USA. He is an actor and producer, known for Terminator: Dark Fate (2019), Agents of S.H.I.E.L.D. (2013) and Bernie (2011). He has been married to Smaranda Luna since February 20, 2011.",
                            ImageUrl = "Images/Actors/Gabriel-Luna-image.jpg",
                            Name = "Gabriel",
                            Surname = "Luna"
                        },
                        new
                        {
                            Id = 7,
                            About = "Few actors in the world have had a career quite as diverse as Leonardo DiCaprio's. DiCaprio has gone from relatively humble beginnings, as a supporting cast member of the sitcom Growing Pains (1985) and low budget horror movies, such as Critters 3 (1991), to a major teenage heartthrob in the 1990s, as the hunky lead actor in movies such as Romeo + Juliet (1996) and Titanic (1997), to then become a leading man in Hollywood blockbusters, made by internationally renowned directors such as Martin Scorsese and Christopher Nolan.\r\n",
                            ImageUrl = "Images/Actors/Leonardo-DiCaprio-image.jpg",
                            Name = "Leonardo",
                            Surname = "DiCaprio"
                        },
                        new
                        {
                            Id = 8,
                            About = "Joseph Leonard Gordon-Levitt was born February 17, 1981 in Los Angeles, California, to Jane Gordon and Dennis Levitt. Joseph was raised in a Jewish family with his late older brother, Dan Gordon-Levitt, who passed away in October 2010. His parents worked for the Pacifica Radio station KPFK-FM and his maternal grandfather, Michael Gordon, had been a well-known movie director. Joseph first became well known for his starring role on NBC's award-winning comedy series 3rd Rock from the Sun (1996). During his six seasons on the show, he won two YoungStar Awards and also shared in three Screen Actors Guild Award® nominations for Outstanding Performance by a Comedy Series Ensemble.",
                            ImageUrl = "Images/Actors/Joseph-Gordon-Levitt-image.jpg",
                            Name = "Joseph",
                            Surname = "Gordon-Levitt"
                        },
                        new
                        {
                            Id = 9,
                            About = "With his breakthrough performance as Eames in Christopher Nolan's sci-fi thriller Inception (2010), English actor Tom Hardy has been brought to the attention of mainstream audiences worldwide. However, the versatile actor has been steadily working on both stage and screen since his television debut in the miniseries Band of Brothers (2001). After being cast in the World War II drama, Hardy left his studies at the prestigious Drama Centre in London and was subsequently cast as Twombly in Ridley Scott's Black Hawk Down (2001) and as the villain Shinzon in Star Trek: Nemesis (2002).",
                            ImageUrl = "Images/Actors/Tom-Hardy-image.jpg",
                            Name = "Tom",
                            Surname = "Hardy"
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.MovieActor", b =>
                {
                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("MovieName", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieName = "Interstellar",
                            ActorId = 1
                        },
                        new
                        {
                            MovieName = "Interstellar",
                            ActorId = 2
                        },
                        new
                        {
                            MovieName = "Interstellar",
                            ActorId = 3
                        },
                        new
                        {
                            MovieName = "Inception",
                            ActorId = 7
                        },
                        new
                        {
                            MovieName = "Inception",
                            ActorId = 8
                        },
                        new
                        {
                            MovieName = "Inception",
                            ActorId = 9
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.MovieGenre", b =>
                {
                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("MovieName", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            MovieName = "Interstellar",
                            GenreId = 1
                        },
                        new
                        {
                            MovieName = "Interstellar",
                            GenreId = 2
                        },
                        new
                        {
                            MovieName = "Interstellar",
                            GenreId = 3
                        },
                        new
                        {
                            MovieName = "Inception",
                            GenreId = 2
                        },
                        new
                        {
                            MovieName = "Inception",
                            GenreId = 3
                        },
                        new
                        {
                            MovieName = "Inception",
                            GenreId = 4
                        },
                        new
                        {
                            MovieName = "Inception",
                            GenreId = 6
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.MovieMark", b =>
                {
                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MovieName", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MovieMarks");

                    b.HasData(
                        new
                        {
                            MovieName = "Interstellar",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.SerialActor", b =>
                {
                    b.Property<string>("SerialName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("SerialName", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("SerialActors");

                    b.HasData(
                        new
                        {
                            SerialName = "The Last of Us",
                            ActorId = 4
                        },
                        new
                        {
                            SerialName = "The Last of Us",
                            ActorId = 5
                        },
                        new
                        {
                            SerialName = "The Last of Us",
                            ActorId = 6
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.SerialGenre", b =>
                {
                    b.Property<string>("SerialName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("SerialName", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("SerialGenres");

                    b.HasData(
                        new
                        {
                            SerialName = "The Last of Us",
                            GenreId = 1
                        },
                        new
                        {
                            SerialName = "The Last of Us",
                            GenreId = 2
                        },
                        new
                        {
                            SerialName = "The Last of Us",
                            GenreId = 3
                        },
                        new
                        {
                            SerialName = "The Last of Us",
                            GenreId = 4
                        },
                        new
                        {
                            SerialName = "The Last of Us",
                            GenreId = 5
                        },
                        new
                        {
                            SerialName = "The Last of Us",
                            GenreId = 6
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.SerialMark", b =>
                {
                    b.Property<string>("SerialName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SerialName", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SerialMarks");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.SoonGenre", b =>
                {
                    b.Property<string>("SoonName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("SoonName", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("SoonGenres");

                    b.HasData(
                        new
                        {
                            SoonName = "John Wick: Chapter 4",
                            GenreId = 4
                        },
                        new
                        {
                            SoonName = "John Wick: Chapter 4",
                            GenreId = 6
                        },
                        new
                        {
                            SoonName = "John Wick: Chapter 4",
                            GenreId = 7
                        },
                        new
                        {
                            SoonName = "Guardians of the Galaxy Vol. 3",
                            GenreId = 2
                        },
                        new
                        {
                            SoonName = "Guardians of the Galaxy Vol. 3",
                            GenreId = 3
                        },
                        new
                        {
                            SoonName = "Guardians of the Galaxy Vol. 3",
                            GenreId = 4
                        },
                        new
                        {
                            SoonName = "Guardians of the Galaxy Vol. 3",
                            GenreId = 8
                        },
                        new
                        {
                            SoonName = "Transformers: Rise of the Beasts",
                            GenreId = 2
                        },
                        new
                        {
                            SoonName = "Transformers: Rise of the Beasts",
                            GenreId = 3
                        },
                        new
                        {
                            SoonName = "Transformers: Rise of the Beasts",
                            GenreId = 4
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VideoLength")
                        .HasColumnType("time");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Twenty years after a fungal outbreak ravages the planet, survivors Joel and Ellie are tasked with a mission that could change everything.",
                            ImageUrl = "Serials/The Last of Us/Season 1/Episode 1/the-last-of-us-S01E01-video-image.jpg",
                            Name = "1. When You're Lost in the Darkness",
                            Number = 1,
                            SeasonId = 1,
                            VideoLength = new TimeSpan(0, 1, 20, 0, 0),
                            VideoUrl = "Serials/The Last of Us/Season 1/Episode 1/the-last-of-us-S01E01-video-720p.mkv"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Joel, Tess, and Ellie traverse through an abandoned and flooded Boston hotel on their way to drop Ellie off with a group of Fireflies.",
                            ImageUrl = "Serials/The Last of Us/Season 1/Episode 2/the-last-of-us-S01E02-video-image.jpg",
                            Name = "2. Infected",
                            Number = 2,
                            SeasonId = 1,
                            VideoLength = new TimeSpan(0, 0, 52, 0, 0),
                            VideoUrl = "Serials/The Last of Us/Season 1/Episode 2/the-last-of-us-S01E02-video-720p.mkv"
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "Images/Genres/drama-image.png",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "Images/Genres/adventure-image.png",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "Images/Genres/sci-fi-image.png",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "Images/Genres/action-image.png",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "Images/Genres/horror-image.png",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "Images/Genres/thriller-image.png",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "Images/Genres/crime-image.png",
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "Images/Genres/comedy-image.png",
                            Name = "Comedy"
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Movie", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProducerId")
                        .HasColumnType("int");

                    b.Property<string>("SearchImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("VideoLength")
                        .HasColumnType("time");

                    b.Property<string>("VideoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("ProducerId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Name = "Interstellar",
                            Age = 13,
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival. Earth's future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind's survival: Interstellar travel.",
                            ImageUrl = "Movies/Interstellar/interstellar-image.jpg",
                            ProducerId = 1,
                            SearchImageUrl = "Movies/Interstellar/interstellar-search-image.jpg",
                            TrailerUrl = "Movies/Interstellar/interstellar-trailer.mp4",
                            VideoDescription = "With humanity teetering on the brink of extinction, a group of astronauts travels through a wormhole in search of another inhabitable planet.",
                            VideoImageUrl = "Movies/Interstellar/interstellar-video-image.jpg",
                            VideoLength = new TimeSpan(0, 2, 50, 0, 0),
                            VideoName = "Interstellar",
                            VideoUrl = "Movies/Interstellar/interstellar-video-720p.mp4",
                            Year = 2014
                        },
                        new
                        {
                            Name = "Inception",
                            Age = 16,
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
                            ImageUrl = "Movies/Inception/inception-image.jpg",
                            ProducerId = 1,
                            SearchImageUrl = "Movies/Inception/inception-search-image.jpg",
                            TrailerUrl = "Movies/Inception/inception-trailer.mp4",
                            VideoDescription = "A troubled thief who extracts secrets from people's dreams takes one last job: leading a dangerous mission to plant an idea in a target's subconscious.",
                            VideoImageUrl = "Movies/Inception/inception-video-image.jpg",
                            VideoLength = new TimeSpan(0, 2, 28, 0, 0),
                            VideoName = "Inception",
                            VideoUrl = "Movies/Inception/inception-video-720p.mkv",
                            Year = 2010
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Best known for his cerebral, often nonlinear, storytelling, acclaimed writer-director Christopher Nolan was born on July 30, 1970, in London, England. Over the course of 15 years of filmmaking, Nolan has gone from low-budget independent films to working on some of the biggest blockbusters ever made.",
                            ImageUrl = "Images/Producers/Christopher-Nolan-image.jpg",
                            Name = "Christopher",
                            Surname = "Nolan"
                        },
                        new
                        {
                            Id = 2,
                            About = "Craig Mazin was born on April 8, 1971 in Brooklyn, New York, USA. He is a producer and writer, known for Chernobyl (2019), The Hangover Part II (2011) and Identity Thief (2013).",
                            ImageUrl = "Images/Producers/Craig-Mazin-image.jpg",
                            Name = "Craig",
                            Surname = "Mazin"
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("SerialName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SerialName");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1,
                            SerialName = "The Last of Us"
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Serial", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProducerId")
                        .HasColumnType("int");

                    b.Property<string>("SearchImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("ProducerId");

                    b.ToTable("Serials");

                    b.HasData(
                        new
                        {
                            Name = "The Last of Us",
                            Age = 16,
                            Description = "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl, who may be humanity's last hope.",
                            ImageUrl = "Serials/The Last of Us/the-last-of-us-image.jpg",
                            ProducerId = 2,
                            SearchImageUrl = "Serials/The Last of Us/the-last-of-us-search-image.jpg",
                            TrailerUrl = "Serials/The Last of Us/the-last-of-us-trailer.mp4",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Soon", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrailerImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Soons");

                    b.HasData(
                        new
                        {
                            Name = "John Wick: Chapter 4",
                            Description = "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
                            OutDate = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerImageUrl = "Soons/John Wick Chapter 4/john-wick-chapter-4-trailer-image.jpg",
                            TrailerUrl = "Soons/John Wick Chapter 4/john-wick-chapter-4-trailer.mp4"
                        },
                        new
                        {
                            Name = "Guardians of the Galaxy Vol. 3",
                            Description = "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.",
                            OutDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerImageUrl = "Soons/Guardians of the Galaxy Vol. 3/guardians-of-the-galaxy-vol-3-trailer-image.jpg",
                            TrailerUrl = "Soons/Guardians of the Galaxy Vol. 3/guardians-of-the-galaxy-vol-3-trailer.mp4"
                        },
                        new
                        {
                            Name = "Transformers: Rise of the Beasts",
                            Description = "Plot unknown. Reportedly based on the 'Transformers' spinoff 'Beast Wars' which feature robots that transform into robotic animals.",
                            OutDate = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerImageUrl = "Soons/Transformers Rise of the Beasts/transformers-rise-of-the-beasts-trailer-image.jpg",
                            TrailerUrl = "Soons/Transformers Rise of the Beasts/transformers-rise-of-the-beasts-trailer.mp4"
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://firebasestorage.googleapis.com/v0/b/novastream-a8167.appspot.com/o/Avatars%2Favatar-1.png?alt=media&token=4fecc3bf-9511-4186-9c25-0347128c0181",
                            Email = "admin@novastream.api",
                            Nickname = "Admin",
                            OldPasswordHash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            PasswordHash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://firebasestorage.googleapis.com/v0/b/novastream-a8167.appspot.com/o/Avatars%2Favatar-1.png?alt=media&token=4fecc3bf-9511-4186-9c25-0347128c0181",
                            Email = "novastream.tester@gmail.com",
                            Nickname = "tyler",
                            OldPasswordHash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            PasswordHash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
                        });
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.MovieActor", b =>
                {
                    b.HasOne("NovaStream.Domain.Entities.Concrete.Actor", "Actor")
                        .WithMany("Movies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaStream.Domain.Entities.Concrete.Movie", "Movie")
                        .WithMany("Actors")
                        .HasForeignKey("MovieName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.MovieGenre", b =>
                {
                    b.HasOne("NovaStream.Domain.Entities.Concrete.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaStream.Domain.Entities.Concrete.Movie", "Movie")
                        .WithMany("Genres")
                        .HasForeignKey("MovieName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.MovieMark", b =>
                {
                    b.HasOne("NovaStream.Domain.Entities.Concrete.Movie", "Movie")
                        .WithMany("Marks")
                        .HasForeignKey("MovieName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaStream.Domain.Entities.Concrete.User", "User")
                        .WithMany("MovieMarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.SerialActor", b =>
                {
                    b.HasOne("NovaStream.Domain.Entities.Concrete.Actor", "Actor")
                        .WithMany("Serials")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaStream.Domain.Entities.Concrete.Serial", "Serial")
                        .WithMany("Actors")
                        .HasForeignKey("SerialName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.SerialGenre", b =>
                {
                    b.HasOne("NovaStream.Domain.Entities.Concrete.Genre", "Genre")
                        .WithMany("SerialGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaStream.Domain.Entities.Concrete.Serial", "Serial")
                        .WithMany("Genres")
                        .HasForeignKey("SerialName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.SerialMark", b =>
                {
                    b.HasOne("NovaStream.Domain.Entities.Concrete.Serial", "Serial")
                        .WithMany("Marks")
                        .HasForeignKey("SerialName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaStream.Domain.Entities.Concrete.User", "User")
                        .WithMany("SerialMarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serial");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Adapters.SoonGenre", b =>
                {
                    b.HasOne("NovaStream.Domain.Entities.Concrete.Genre", "Genre")
                        .WithMany("SoonGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaStream.Domain.Entities.Concrete.Soon", "Soon")
                        .WithMany("Genres")
                        .HasForeignKey("SoonName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Soon");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Episode", b =>
                {
                    b.HasOne("NovaStream.Domain.Entities.Concrete.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Movie", b =>
                {
                    b.HasOne("NovaStream.Domain.Entities.Concrete.Producer", "Producer")
                        .WithMany("Movies")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Season", b =>
                {
                    b.HasOne("NovaStream.Domain.Entities.Concrete.Serial", "Serial")
                        .WithMany("Seasons")
                        .HasForeignKey("SerialName")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Serial", b =>
                {
                    b.HasOne("NovaStream.Domain.Entities.Concrete.Producer", "Producer")
                        .WithMany("Serials")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Actor", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Serials");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Genre", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("SerialGenres");

                    b.Navigation("SoonGenres");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Movie", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Genres");

                    b.Navigation("Marks");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Producer", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Serials");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Serial", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Genres");

                    b.Navigation("Marks");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.Soon", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("NovaStream.Domain.Entities.Concrete.User", b =>
                {
                    b.Navigation("MovieMarks");

                    b.Navigation("SerialMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
